addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=package-ubuntu-1604
  - INSTANCE=package-centos-6
  - INSTANCE=package-centos-7
  - INSTANCE=package-debian-8
#  - INSTANCE=source-ubuntu-1604 fails to find ruby libs during compile
  - INSTANCE=source-centos-6
  - INSTANCE=source-centos-7
  - INSTANCE=source-debian-8

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
